Update lis3mdl_lsm6ds_test.py
adafruit/Adafruit_CircuitPython_LIS3MDL pull request #14
Opened 2020-11-05 18:45 UTC by Breefield

adafruit_lsm6ds is a module now, these imports change

2020-11-06 00:44 UTC, FoamyGuy requested changes
@Breefield thanks for fixing these! Can you make the sub-module names lowercase so that they'll match the name of the file that that they're inside of. 
like: 
```python
from adafruit_lsm6ds.lsm6dox import LSM6DSOX as LSM6DS
```
Other than that these changes look good to me. Tested successfully on Feather nrf52840.

2020-11-06 23:31 UTC, Breefield commented
👍

2020-11-06 23:46 UTC, FoamyGuy commented on examples/lis3mdl_lsm6ds_test.py
> +from adafruit_lsm6ds.lsm6Dsox import LSM6DSOX as LSM6DS
One more capital `D` snuck in here.

2020-11-07 00:55 UTC, FoamyGuy approved these changes
Looks good to me. Thanks again @Breefield

2020-11-09 18:26 UTC, merged